[package]
name = "spandex-hyphenation"
version = "0.7.3"

authors = ["Thomas Forgione <thomas@forgione.fr>", "Andrew <andrew@banausia.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-spandex/hyphenation"
homepage = "https://github.com/rust-spandex/hyphenation"

readme = "README.md"
description = "Knuth-Liang hyphenation for a variety of languages"
keywords = ["text", "typesetting"]


include = ["**/*.rs", "**/Cargo.toml", "dictionaries/*", "patterns/*",
           "README.md", "LICENSE*"]
build = "build.rs"


[features]
embed_all = ["pocket-resources"]
build_dictionaries = []

# Unicode normalization.
#
# HEED: these features are mutually exclusive; only one may be passed to
# rustc/cargo as an argument. `build.rs` ensures that these multiple "features"
# effectively behave as a single, configurable parameter: were the user to
# select more than one normalization form, the build will fail.
nfc = ["unicode-normalization"]
nfd = ["unicode-normalization"]
nfkc = ["unicode-normalization"]
nfkd = ["unicode-normalization"]


[workspace]
members = ["hyphenation_commons"]

[dependencies]
hyphenation_commons = { path = "hyphenation_commons", version = "0.7.1" }
atlatl = { version = "0.1.2", features = ["serde"] }
bincode = "1.0"
serde = "1.0"

[build-dependencies]
hyphenation_commons = { path = "hyphenation_commons", version = "0.7.1" }
atlatl = { version = "0.1.2", features = ["serde"] }
bincode = "1.0"
serde = "1.0"
pocket-resources = { version  = "0.3", optional = true }
unicode-normalization = { version  = "0.1", optional = true }

[dev-dependencies]
lazy_static = "1.1"
quickcheck = "0.7"
unicode-segmentation = "1.2"
